[package]
name = "gha_ping"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
git2 = { workspace = true }
ratelimit = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
