[workspace]
resolver = "2"
members = [
    "gha_ping"
]

[workspace.dependencies]
axum = { version = "0.8" }
ratelimit = { version = "0.10" }
tokio = { version = "1.0", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
