name: Notify server
on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  notify:
    name: Post /update to server
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        shell: bash
        env:
          SERVER_NOTIFY_URL: ${{ secrets.SERVER_NOTIFY_URL }}
        run: |
          echo 'SERVER_RESPONSE_CODE=$(echo $SERVER_NOTIFY_URL | xargs curl -s -o /dev/null -w "%{http_code}" -X POST)' >> $GITHUB_ENV
      - name: Fail on wrong HTTP response code
        if: ${{ env.SERVER_RESPONSE_CODE != '204' }}
        shell: bash
        run: |
          echo "::error::Server responded with unexpected code: ${{ env.SERVER_RESPONSE_CODE }}"
          exit 1
