name: Notify server
on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  notify:
    name: Post /update to server
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        shell: bash
        env:
          SERVER_NOTIFY_URL: ${{ secrets.SERVER_NOTIFY_URL }}
        run: |
          curlout=$(echo $SERVER_NOTIFY_URL | xargs curl -s -o /dev/null -w "%{http_code}" -X POST)
          if [ $? -eq 0 ]; then
            echo "SERVER_RESPONSE_CODE=$curlout" >> "$GITHUB_ENV"
          else
            echo "::error::Curl failed with code: $?"
            exit 1
          fi
      - name: Log response code
        shell: bash
        run: |
          echo "Server responded with code: ${{ env.SERVER_RESPONSE_CODE }}"
      - name: Fail on wrong HTTP response code
        if: ${{ env.SERVER_RESPONSE_CODE != '204' }}
        shell: bash
        run: |
          echo "::error::Server responded with unexpected code: ${{ env.SERVER_RESPONSE_CODE }}"
          exit 1
